name = "insightbackend"
compatibility_date = "2024-07-16"

[vars]
DATABASE_URL = "mongodb+srv://siddhantdaryanani:siddhant@cluster0.ic6amah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
JWT_SECRET = "secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

[ai]
binding = "AI"